### ISSUE TITLE
你好，请问有在imagenet上跑过模型吗？需要什么样的机器配置啊

### ISSUE THREAD

**Issue by weitingyuk** [13952522076/ResidualAttention#1]

**Comment by ma-xu** [comment]
没有，可能需要几个V100的GPUs 来跑ImageNet.
不过这个代码是为了我的文章的，不是“Residual Attention Network for Image Classification” 这篇。

**Comment by ma-xu** [comment]
我将在接下来两月中进行在ImageNet上进行相关试验。模型会第一时间公布出来。
